version = 1

[[analyzers]]
name = "javascript"
enabled = true
minimum_version = "16.0"
  [analyzers.meta]
  languages = ["javascript"]
  files = ["backend/**/*.js"]
  skip_dirs = ["node_modules", "frontend/node_modules"]

[[analyzers]]
name = "python"
enabled = false
  [analyzers.meta]
  skip_dirs = ["venv", "backend/venv"]
