version = 1

[[analyzers]]
name = "javascript"
enabled = true
minimum_version = "23.0"
  [analyzers.settings]
  max_line_length = 100
  allow_implicit_any = false

[[analyzers]]
name = "python"
enabled = false
