version = 1

[[analyzers]]
name = "javascript"
enabled = true
  [analyzers.meta]
  skip_files = ["node_modules/**"]

[[analyzers]]
name = "python"
enabled = true
  [analyzers.meta]
  skip_files = ["venv/**"]
