# render.yaml
services:
  - type: web
    name: tradesync-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent -w 1 wsgi:application
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false