services:
  # Backend service
  - type: web
    name: tradesync-backend
    env: node
    buildCommand: cd backend-node && npm install
    startCommand: cd backend-node && node server.js
    envVars:
      - key: APCA_API_KEY_ID
        sync: false
      - key: APCA_API_SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000

  # Frontend service
  - type: web
    name: tradesync-frontend
    env: node
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npx serve -s build -l $PORT
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          name: tradesync-backend
          type: web
          property: host
      - key: PORT
        value: 3000
